---
name: PHP CI/CD Pipeline

on:
 push:
  branches: [main]
 workflow_dispatch:
  inputs:
   environment:
    description: 'Target deployment environment'
    required: false
    default: 'staging'
    type: string

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Set up PHP
     uses: shivammathur/setup-php@v2
     with:
      php-version: '8.2'

   - name: Install dependencies
     run: |
      composer install

   - name: Run Composer Security Audit
     run: |
      composer audit --no-interaction --no-dev

   - name: Run PHPUnit tests with reports
     run: |
      ./vendor/bin/phpunit
 deploy:
  needs: test
  runs-on: ubuntu-latest
  steps:
   - name: Set deployment environment
     run: |
      # When var supplied manually, if no environment variable input at runtime,
      # use Staging, else Prod.
      if [ -z "${{ github.event.inputs.environment }}" ]; then
       echo "TARGET_ENV=staging" >> $GITHUB_ENV
      else
       echo "TARGET_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
      fi
      # This is only for when yaml is run with github workflow,
      # i.e. inputs.environment is empty string.
      if [ -z "$TARGET_ENV" ]; then
       echo "TARGET_ENV is not set. Defaulting to staging."
       TARGET_ENV="staging"
      fi

   - name: Deploy to FastComet via SSH
     uses: appleboy/ssh-action@v0.1.10
     with:
      host: ${{ secrets.FASTCOMET_HOST }}
      username: ${{ secrets.FASTCOMET_USER }}
      key: ${{ secrets.FASTCOMET_SSH_KEY }}
      script: |
       if [ "$TARGET_ENV" = "production" ]; then
        echo "Running production deployment tasks..."
        # Add production-specific commands here
        cd /home5/systema1/devsecops.systematicdefence.tech/
        git pull origin main
       elif [ "$TARGET_ENV" = "staging" ]; then
        echo "Running staging deployment tasks..."
        # Add staging-specific commands here
        cd /home5/systema1/testapiserver.systematicdefence.tech/
        git pull origin main
       elif [ "$TARGET_ENV" = "dev" ]; then
        echo "Running dev deployment tasks..."
        # Add dev-specific commands here
       else
        echo "Unknown environment: $TARGET_ENV"
        exit 1
       fi
