---
name: PHP CI/CD Pipeline

on:
 push:
  branches: [main]

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Set up PHP
     uses: shivammathur/setup-php@v2
     with:
      php-version: '8.2'

   - name: Install dependencies
     run: |
      composer install

   - name: Run Composer Security Audit
     run: |
      composer audit --no-interaction --no-dev

   - name: Run PHPUnit tests with reports
     run: |
      ./vendor/bin/phpunit
 deploy:
  needs: test
  runs-on: ubuntu-latest
  steps:
   - name: Deploy to FastComet via SSH
     uses: appleboy/ssh-action@v0.1.10
     with:
      host: ${{ secrets.FASTCOMET_HOST }}
      username: ${{ secrets.FASTCOMET_USER }}
      key: ${{ secrets.FASTCOMET_SSH_KEY }}
      script: |
       cd /home5/systema1/devsecops.systematicdefence.tech/
       git pull origin main
